name: base
idx: 10
arch: resnet
layers: 56
width_mult: 1.0
depth_mult: 1.0
model_mult: 0.0
dataset: cifar100
datapath: ../data
workers: 8
batch_size: 128
config: []
run_type: train
init: null
init_opt: false
resume: null
eval: null
gpu:
- 0
epochs: 300
optimizer: SGD
lr: 0.1
momentum: 0.9
weight_decay: 0.0001
nesterov: false
scheduler: cosine
step_size: 100
milestones:
- 100
- 200
gamma: 0.1
sched_batch: true
print_freq: 100
