arch: resnet
layers: 20
width_mult: 1.0
depth_mult: 1.0
model_mult: 0.0
dataset: cifar100
datapath: ../data
workers: 8
batch_size: 128
yamls: []
run_type: train
load: null
resume: false
device: gpu
gpu:
- 0
epochs: 300
optimizer: SGD
lr: 0.1
momentum: 0.9
weight_decay: 0.0005
nesterov: false
lr_scheduler: cosine
step_size: 100
step_milestones:
- 100
- 200
step_gamma: 0.1
step_location: batch
warmup: 5
name: base
idx: 0
print_freq: 100
